config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "local_forecasts/index"
  post "local_forecasts/search"
  root "local_forecasts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
  end
end

app/controllers/local_forecasts_controller.rb
# frozen_string_literal: true

class LocalForecastsController < ApplicationController
  rescue_from ArgumentError, with: :invalid_location
  def index
  end

  def search
    @location = params[:location]
    @forecast = LocalForecastService.new(@location).call&.deep_symbolize_keys
    if @forecast
      respond_to do |format|
        format.turbo_stream
      end
    else
      flash.now[:alert] = "Location not found"
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend(
            "flash-message",
            partial: "layouts/flash"
          )
        end
      end
    end
  end

  private

  def invalid_location
    flash.now[:alert] = "Location cannot be blank"
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.prepend(
          "flash-message",
          partial: "layouts/flash"
        )
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/local_forecasts_helper.rb
# frozen_string_literal: true

module LocalForecastsHelper
  def weather_code_to_weather(code) # rubocop:disable Metrics/MethodLength
    weather_map = {
      0 => "Clear sky",
      1 => "Mainly clear",
      2 => "Partly cloudy",
      3 => "Overcast",
      45 => "Fog",
      48 => "Fog and depositing rime fog",
      51 => "Drizzle: Light intensity",
      53 => "Drizzle: Moderate intensity",
      55 => "Drizzle: Dense intensity",
      56 => "Freezing Drizzle: Light intensity",
      57 => "Freezing Drizzle: Dense intensity",
      61 => "Rain: Slight intensity",
      63 => "Rain: Moderate intensity",
      65 => "Rain: Heavy intensity",
      66 => "Freezing Rain: Light intensity",
      67 => "Freezing Rain: Heavy intensity",
      71 => "Snow fall: Slight intensity",
      73 => "Snow fall: Moderate intensity",
      75 => "Snow fall: Heavy intensity",
      77 => "Snow grains",
      80 => "Rain showers: Slight",
      81 => "Rain showers: Moderate",
      82 => "Rain showers: Violent",
      85 => "Snow showers slight",
      86 => "Snow showers heavy",
      95 => "Thunderstorm: Slight or moderate",
      96 => "Thunderstorm with slight hail",
      99 => "Thunderstorm with heavy hail"
    }
    weather_map[code]
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="flash_removals"
    data-action="animationend->flash_removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for?(:title) ? strip_tags(yield(:title)) : "Local Forecasting" %></title>
    <meta name="apple-mobile-web-app-title" content="Local Forecasting">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/local_forecasts/_forecast_data.html.erb
<div id="forecast-map" style="height: 400px; width: 100%;"></div>

<script>
  function initMap() {
    var forecastLocation = { lat: <%= @forecast[:latitude] %>, lng: <%= @forecast[:longitude] %> };
    var map = new google.maps.Map(document.getElementById('forecast-map'), {
      zoom: 8,
      center: forecastLocation
    });
    var marker = new google.maps.Marker({
      position: forecastLocation,
      map: map
    });
  }
</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_APIKEY'] %>&callback=initMap">
</script>

<div class="forecast-details">
  <div class="left">
    <p>Current Temperature: <%= @forecast.dig(:current, :temperature_2m) %>°F</p>
    <p>Current Weather: <%= weather_code_to_weather(@forecast.dig(:current, :weather_code)) %></p>
  </div>
  <div class="right">
    <p>Max Temperature: <%= @forecast.dig(:daily, :temperature_2m_max).first %>°F</p>
    <p>Min Temperature: <%= @forecast.dig(:daily, :temperature_2m_min).first %>°F</p>
  </div>
</div>

app/views/local_forecasts/_search_field.html.erb
<%= form_with url: local_forecasts_search_path, method: :post, data: {turbo_stream: true}, id: 'search_forecast' do %>
  <%= label_tag :location, "Enter Address:" %>
  <%= text_field_tag :location, @location, placeholder: "e.g., 1327 Murray Dr, Jacksonville - FL" %>
  <%= submit_tag "Get Forecast" %>
<% end %>

app/views/local_forecasts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Local Forecasting</title>
  <style>

  </style>
</head>
<body>
  <div class="forecast-container">
    <h1>Local Forecasting</h1>
    <%= render "local_forecasts/search_field" %>
    <div class="flash" id="flash-message"></div>
    <div id='forecast_result'>
    </div>
  </div>
</body>
</html>

app/views/local_forecasts/search.turbo_stream.erb
<%= turbo_stream.update("forecast_result", partial: "forecast_data", locals: {forecast: @forecast}) %>